export enum StatusVenda {
    PENDENTE = 'PENDENTE',
    APROVADA = 'APROVADA',
    REPROVADA = 'REPROVADA',
    CANCELADO = 'CANCELADO',
    EM_PROCESSAMENTO = 'EM_PROCESSAMENTO',
    EM_TRANSITO = 'EM_TRANSITO',
    ENTREGUE = 'ENTREGUE',
    EM_TROCA = 'EM_TROCA',
    TROCA_AUTORIZADA = 'TROCA_AUTORIZADA',
    TROCA_CONCLUIDA = 'TROCA_CONCLUIDA',
    TROCA_SOLICITADA = 'TROCA_SOLICITADA',
    TROCA_RECUSADA = 'TROCA_RECUSADA',
    DEVOLUCAO_SOLICITADA = 'DEVOLUÇÃO_SOLICITADA',
    DEVOLUCAO_RECUSADA = 'DEVOLUCAO_RECUSADA',
    DEVOLUCAO_CONCLUIDA = 'DEVOLUCAO_CONCLUIDA'
  }